package org.ezcomputing.server.dao.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
/**
 * @author Bo Zhao
 *
 */
@DynamoDBDocument
@DynamoDBTable(tableName = "JobScheduler")
public class JobScheduler {
	
	public JobScheduler() {
		
	}
	
	public String toName() {
		return type+" "+ String.format("%02d", hours)+":"+String.format("%02d", minutes);
	}
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	
	@DynamoDBAttribute(attributeName = "jobId")
	private String jobId;
	
	@DynamoDBAttribute(attributeName = "type")
	private String type;
	
	@DynamoDBAttribute(attributeName = "days")
	private int days;
	
	@DynamoDBAttribute(attributeName = "hours")
	private int hours;
	
	@DynamoDBAttribute(attributeName = "minutes")
	private int minutes;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getJobId() {
		return jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getDays() {
		return days;
	}

	public void setDays(int days) {
		this.days = days;
	}

	public int getHours() {
		return hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	public int getMinutes() {
		return minutes;
	}

	public void setMinutes(int minutes) {
		this.minutes = minutes;
	}

	
	
	
}
