package org.ezcomputing.server.dao.dto;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * @author Bo Zhao
 *
 */

@DynamoDBTable(tableName = "source-hub")
public class SourceHub {
	
	public SourceHub() {
		
	}

	@DynamoDBHashKey(attributeName = "function-name")
    private String name;

	@DynamoDBRangeKey(attributeName = "version")
    private String version;

    @DynamoDBAttribute(attributeName = "source")
    private String source;

    @DynamoDBAttribute(attributeName = "sample-request")
    private String sampleRequest;
    
    @DynamoDBAttribute(attributeName = "sample-response")
    private String sampleResponse;
    
    
    @DynamoDBAttribute(attributeName = "status")
    private String status = Constants.Source_HUB_STATUS.pending;
    
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date createDate;
    
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updateDate;
    
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getSampleRequest() {
		return sampleRequest;
	}

	public void setSampleRequest(String sampleRequest) {
		this.sampleRequest = sampleRequest;
	}

	public String getSampleResponse() {
		return sampleResponse;
	}

	public void setSampleResponse(String sampleResponse) {
		this.sampleResponse = sampleResponse;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
    
    
}