package org.ezcomputing.server.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.graalvm.polyglot.HostAccess;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
/**
 * @author Bo Zhao
 *
 */
@DynamoDBTable(tableName = "user")
public class User {

	public User() {

	}
	@DynamoDBHashKey(attributeName = "email")
	private String email;

	// cognitive key
	@DynamoDBAttribute(attributeName = "subject")
	private String subject;

	@DynamoDBAttribute(attributeName = "familyName")
	private String familyName;

	@DynamoDBAttribute(attributeName = "givenName")
	private String givenName;

	@DynamoDBAttribute(attributeName = "workerList")
	private List<String> workerList = new ArrayList<String>();
	
	//for example: ROLE_ADMIN;ROLE_USER;ROLE_TESTER
	@DynamoDBAttribute(attributeName = "authorityList")
	private String authorityList;
	

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private Date createDate;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private Date updateDate;

	
	public String toFullName() {
		return this.getGivenName() + " " + this.getFamilyName();
	}
	public String toShortFullName() {
		return this.getGivenName() + " " + StringUtils.substring(this.getFamilyName(), 0, 0);
	}
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public List<String> getWorkerList() {
		return workerList;
	}

	public void setWorkerList(List<String> workerList) {
		this.workerList = workerList;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getFamilyName() {
		return familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	public String getGivenName() {
		return givenName;
	}

	public void setGivenName(String givenName) {
		this.givenName = givenName;
	}
	public String getAuthorityList() {
		return authorityList;
	}
	public void setAuthorityList(String authorityList) {
		this.authorityList = authorityList;
	}

}
