package org.ezcomputing.server.dao.dto;


import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * @author Bo Zhao
 *
 */

@DynamoDBTable(tableName = "worker")
public class Worker {
	
	
	
	public Worker() {
		
	}

	
	
	@DynamoDBHashKey(attributeName = "id")
    //@DynamoDBAutoGeneratedKey
    private String id;
	
	@DynamoDBAttribute(attributeName = "name")
    private String name;
	
	@DynamoDBAttribute(attributeName = "email")
    private String email;
	
	@DynamoDBAttribute(attributeName = "ownerName")
    private String ownerName;
	
	@DynamoDBAttribute(attributeName = "workerStatus")
    private String workerStatus = Constants.WORKER_STATUS.offline;
	
	
	@DynamoDBAttribute(attributeName = "apiVersion")
    private int apiVersion;
	
	
	@DynamoDBAttribute(attributeName = "ip")
    private String ip;
	
	@DynamoDBAttribute(attributeName = "systemInfo")
    private String systemInfo;
	
	@DynamoDBAttribute(attributeName = "verified")
    private boolean verified = false;
    
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date createDate;
    
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updateDate;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private Long updateTimestamp;

	public String getWorkerStatus() {
		return workerStatus;
	}

	public void setWorkerStatus(String workerStatus) {
		this.workerStatus = workerStatus;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Long getUpdateTimestamp() {
		return updateTimestamp;
	}

	public void setUpdateTimestamp(Long updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getSystemInfo() {
		return systemInfo;
	}

	public void setSystemInfo(String systemInfo) {
		this.systemInfo = systemInfo;
	}

	public boolean isVerified() {
		return verified;
	}

	public void setVerified(boolean verified) {
		this.verified = verified;
	}

	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public int getApiVersion() {
		return apiVersion;
	}

	public void setApiVersion(int apiVersion) {
		this.apiVersion = apiVersion;
	}

	
    
}
